apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: folding-at-home-gpu
  name: folding-at-home-gpu
spec:
  progressDeadlineSeconds: 300
  replicas: 2
  selector:
    matchLabels:
      app: folding-at-home-gpu
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: folding-at-home-gpu
    spec:
      containers:
        - image: sdanaipat/folding-at-home
          name: folding-at-home-gpu
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2000m
              memory: 8Gi
              nvidia.com/gpu: 1
            limits:
              cpu: 4000m
              memory: 16Gi
              nvidia.com/gpu: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        kubernetes.io/hostname: titan
